//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("GRHProjectModel", "FK_SIGNE_CONTRAT", "CONTRAT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projet_Developpement.CONTRAT), "SIGNE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.SIGNE), true)]
[assembly: EdmRelationshipAttribute("GRHProjectModel", "FK_EST_GERE_PAR_EMPLOYE", "EMPLOYE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projet_Developpement.EMPLOYE), "EST_GERE_PAR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.EST_GERE_PAR), true)]
[assembly: EdmRelationshipAttribute("GRHProjectModel", "FK_SIGNE_EMPLOYE", "EMPLOYE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projet_Developpement.EMPLOYE), "SIGNE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.SIGNE), true)]
[assembly: EdmRelationshipAttribute("GRHProjectModel", "FK_EST_GERE_PAR_SERVICE", "SERVICE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projet_Developpement.SERVICE), "EST_GERE_PAR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.EST_GERE_PAR), true)]
[assembly: EdmRelationshipAttribute("GRHProjectModel", "AVOIR", "ABSENCE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.ABSENCE), "EMPLOYE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.EMPLOYE))]
[assembly: EdmRelationshipAttribute("GRHProjectModel", "DISPOSE", "COMPETENCE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.COMPETENCE), "EMPLOYE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.EMPLOYE))]
[assembly: EdmRelationshipAttribute("GRHProjectModel", "POSSEDE", "DIPLOME", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.DIPLOME), "EMPLOYE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.EMPLOYE))]
[assembly: EdmRelationshipAttribute("GRHProjectModel", "FK_EMPLOYE_METIER", "METIER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projet_Developpement.METIER), "EMPLOYE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.EMPLOYE), true)]
[assembly: EdmRelationshipAttribute("GRHProjectModel", "FK_EMPLOYE_SERVICE", "SERVICE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Projet_Developpement.SERVICE), "EMPLOYE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet_Developpement.EMPLOYE), true)]

#endregion

namespace Projet_Developpement
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class GRHProjectEntities1 : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet GRHProjectEntities1 à l'aide de la chaîne de connexion trouvée dans la section 'GRHProjectEntities1' du fichier de configuration d'application.
        /// </summary>
        public GRHProjectEntities1() : base("name=GRHProjectEntities1", "GRHProjectEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet GRHProjectEntities1.
        /// </summary>
        public GRHProjectEntities1(string connectionString) : base(connectionString, "GRHProjectEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet GRHProjectEntities1.
        /// </summary>
        public GRHProjectEntities1(EntityConnection connection) : base(connection, "GRHProjectEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<ABSENCE> ABSENCE
        {
            get
            {
                if ((_ABSENCE == null))
                {
                    _ABSENCE = base.CreateObjectSet<ABSENCE>("ABSENCE");
                }
                return _ABSENCE;
            }
        }
        private ObjectSet<ABSENCE> _ABSENCE;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<COMPETENCE> COMPETENCE
        {
            get
            {
                if ((_COMPETENCE == null))
                {
                    _COMPETENCE = base.CreateObjectSet<COMPETENCE>("COMPETENCE");
                }
                return _COMPETENCE;
            }
        }
        private ObjectSet<COMPETENCE> _COMPETENCE;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<CONTRAT> CONTRAT
        {
            get
            {
                if ((_CONTRAT == null))
                {
                    _CONTRAT = base.CreateObjectSet<CONTRAT>("CONTRAT");
                }
                return _CONTRAT;
            }
        }
        private ObjectSet<CONTRAT> _CONTRAT;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<DIPLOME> DIPLOME
        {
            get
            {
                if ((_DIPLOME == null))
                {
                    _DIPLOME = base.CreateObjectSet<DIPLOME>("DIPLOME");
                }
                return _DIPLOME;
            }
        }
        private ObjectSet<DIPLOME> _DIPLOME;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<EMPLOYE> EMPLOYE
        {
            get
            {
                if ((_EMPLOYE == null))
                {
                    _EMPLOYE = base.CreateObjectSet<EMPLOYE>("EMPLOYE");
                }
                return _EMPLOYE;
            }
        }
        private ObjectSet<EMPLOYE> _EMPLOYE;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<EST_GERE_PAR> EST_GERE_PAR
        {
            get
            {
                if ((_EST_GERE_PAR == null))
                {
                    _EST_GERE_PAR = base.CreateObjectSet<EST_GERE_PAR>("EST_GERE_PAR");
                }
                return _EST_GERE_PAR;
            }
        }
        private ObjectSet<EST_GERE_PAR> _EST_GERE_PAR;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<HISTORIQUE> HISTORIQUE
        {
            get
            {
                if ((_HISTORIQUE == null))
                {
                    _HISTORIQUE = base.CreateObjectSet<HISTORIQUE>("HISTORIQUE");
                }
                return _HISTORIQUE;
            }
        }
        private ObjectSet<HISTORIQUE> _HISTORIQUE;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<METIER> METIER
        {
            get
            {
                if ((_METIER == null))
                {
                    _METIER = base.CreateObjectSet<METIER>("METIER");
                }
                return _METIER;
            }
        }
        private ObjectSet<METIER> _METIER;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<SERVICE> SERVICE
        {
            get
            {
                if ((_SERVICE == null))
                {
                    _SERVICE = base.CreateObjectSet<SERVICE>("SERVICE");
                }
                return _SERVICE;
            }
        }
        private ObjectSet<SERVICE> _SERVICE;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<SIGNE> SIGNE
        {
            get
            {
                if ((_SIGNE == null))
                {
                    _SIGNE = base.CreateObjectSet<SIGNE>("SIGNE");
                }
                return _SIGNE;
            }
        }
        private ObjectSet<SIGNE> _SIGNE;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet ABSENCE. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToABSENCE(ABSENCE aBSENCE)
        {
            base.AddObject("ABSENCE", aBSENCE);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet COMPETENCE. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCOMPETENCE(COMPETENCE cOMPETENCE)
        {
            base.AddObject("COMPETENCE", cOMPETENCE);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet CONTRAT. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCONTRAT(CONTRAT cONTRAT)
        {
            base.AddObject("CONTRAT", cONTRAT);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet DIPLOME. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToDIPLOME(DIPLOME dIPLOME)
        {
            base.AddObject("DIPLOME", dIPLOME);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet EMPLOYE. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToEMPLOYE(EMPLOYE eMPLOYE)
        {
            base.AddObject("EMPLOYE", eMPLOYE);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet EST_GERE_PAR. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToEST_GERE_PAR(EST_GERE_PAR eST_GERE_PAR)
        {
            base.AddObject("EST_GERE_PAR", eST_GERE_PAR);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet HISTORIQUE. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToHISTORIQUE(HISTORIQUE hISTORIQUE)
        {
            base.AddObject("HISTORIQUE", hISTORIQUE);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet METIER. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMETIER(METIER mETIER)
        {
            base.AddObject("METIER", mETIER);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet SERVICE. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSERVICE(SERVICE sERVICE)
        {
            base.AddObject("SERVICE", sERVICE);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet SIGNE. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSIGNE(SIGNE sIGNE)
        {
            base.AddObject("SIGNE", sIGNE);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet sysdiagrams. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="ABSENCE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ABSENCE : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet ABSENCE.
        /// </summary>
        /// <param name="aBSENCE_ID">Valeur initiale de la propriété ABSENCE_ID.</param>
        /// <param name="aBSENCE_DATEDEB">Valeur initiale de la propriété ABSENCE_DATEDEB.</param>
        /// <param name="aBSENCE_DATEFIN">Valeur initiale de la propriété ABSENCE_DATEFIN.</param>
        /// <param name="aBSENCE_DESCRIPTION">Valeur initiale de la propriété ABSENCE_DESCRIPTION.</param>
        public static ABSENCE CreateABSENCE(global::System.Int32 aBSENCE_ID, global::System.DateTime aBSENCE_DATEDEB, global::System.DateTime aBSENCE_DATEFIN, global::System.String aBSENCE_DESCRIPTION)
        {
            ABSENCE aBSENCE = new ABSENCE();
            aBSENCE.ABSENCE_ID = aBSENCE_ID;
            aBSENCE.ABSENCE_DATEDEB = aBSENCE_DATEDEB;
            aBSENCE.ABSENCE_DATEFIN = aBSENCE_DATEFIN;
            aBSENCE.ABSENCE_DESCRIPTION = aBSENCE_DESCRIPTION;
            return aBSENCE;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ABSENCE_ID
        {
            get
            {
                return _ABSENCE_ID;
            }
            set
            {
                if (_ABSENCE_ID != value)
                {
                    OnABSENCE_IDChanging(value);
                    ReportPropertyChanging("ABSENCE_ID");
                    _ABSENCE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ABSENCE_ID");
                    OnABSENCE_IDChanged();
                }
            }
        }
        private global::System.Int32 _ABSENCE_ID;
        partial void OnABSENCE_IDChanging(global::System.Int32 value);
        partial void OnABSENCE_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ABSENCE_DATEDEB
        {
            get
            {
                return _ABSENCE_DATEDEB;
            }
            set
            {
                OnABSENCE_DATEDEBChanging(value);
                ReportPropertyChanging("ABSENCE_DATEDEB");
                _ABSENCE_DATEDEB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ABSENCE_DATEDEB");
                OnABSENCE_DATEDEBChanged();
            }
        }
        private global::System.DateTime _ABSENCE_DATEDEB;
        partial void OnABSENCE_DATEDEBChanging(global::System.DateTime value);
        partial void OnABSENCE_DATEDEBChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ABSENCE_DATEFIN
        {
            get
            {
                return _ABSENCE_DATEFIN;
            }
            set
            {
                OnABSENCE_DATEFINChanging(value);
                ReportPropertyChanging("ABSENCE_DATEFIN");
                _ABSENCE_DATEFIN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ABSENCE_DATEFIN");
                OnABSENCE_DATEFINChanged();
            }
        }
        private global::System.DateTime _ABSENCE_DATEFIN;
        partial void OnABSENCE_DATEFINChanging(global::System.DateTime value);
        partial void OnABSENCE_DATEFINChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ABSENCE_DESCRIPTION
        {
            get
            {
                return _ABSENCE_DESCRIPTION;
            }
            set
            {
                OnABSENCE_DESCRIPTIONChanging(value);
                ReportPropertyChanging("ABSENCE_DESCRIPTION");
                _ABSENCE_DESCRIPTION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ABSENCE_DESCRIPTION");
                OnABSENCE_DESCRIPTIONChanged();
            }
        }
        private global::System.String _ABSENCE_DESCRIPTION;
        partial void OnABSENCE_DESCRIPTIONChanging(global::System.String value);
        partial void OnABSENCE_DESCRIPTIONChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "AVOIR", "EMPLOYE")]
        public EntityCollection<EMPLOYE> LesEmployes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EMPLOYE>("GRHProjectModel.AVOIR", "EMPLOYE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EMPLOYE>("GRHProjectModel.AVOIR", "EMPLOYE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="COMPETENCE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COMPETENCE : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet COMPETENCE.
        /// </summary>
        /// <param name="cOMP_ID">Valeur initiale de la propriété COMP_ID.</param>
        public static COMPETENCE CreateCOMPETENCE(global::System.Int32 cOMP_ID)
        {
            COMPETENCE cOMPETENCE = new COMPETENCE();
            cOMPETENCE.COMP_ID = cOMP_ID;
            return cOMPETENCE;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 COMP_ID
        {
            get
            {
                return _COMP_ID;
            }
            set
            {
                if (_COMP_ID != value)
                {
                    OnCOMP_IDChanging(value);
                    ReportPropertyChanging("COMP_ID");
                    _COMP_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("COMP_ID");
                    OnCOMP_IDChanged();
                }
            }
        }
        private global::System.Int32 _COMP_ID;
        partial void OnCOMP_IDChanging(global::System.Int32 value);
        partial void OnCOMP_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMP_NOM
        {
            get
            {
                return _COMP_NOM;
            }
            set
            {
                OnCOMP_NOMChanging(value);
                ReportPropertyChanging("COMP_NOM");
                _COMP_NOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMP_NOM");
                OnCOMP_NOMChanged();
            }
        }
        private global::System.String _COMP_NOM;
        partial void OnCOMP_NOMChanging(global::System.String value);
        partial void OnCOMP_NOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMP_DETAIL
        {
            get
            {
                return _COMP_DETAIL;
            }
            set
            {
                OnCOMP_DETAILChanging(value);
                ReportPropertyChanging("COMP_DETAIL");
                _COMP_DETAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMP_DETAIL");
                OnCOMP_DETAILChanged();
            }
        }
        private global::System.String _COMP_DETAIL;
        partial void OnCOMP_DETAILChanging(global::System.String value);
        partial void OnCOMP_DETAILChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "DISPOSE", "EMPLOYE")]
        public EntityCollection<EMPLOYE> LesEmployes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EMPLOYE>("GRHProjectModel.DISPOSE", "EMPLOYE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EMPLOYE>("GRHProjectModel.DISPOSE", "EMPLOYE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="CONTRAT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CONTRAT : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet CONTRAT.
        /// </summary>
        /// <param name="cONTRAT_NUM">Valeur initiale de la propriété CONTRAT_NUM.</param>
        /// <param name="cONTRAT_NOM">Valeur initiale de la propriété CONTRAT_NOM.</param>
        public static CONTRAT CreateCONTRAT(global::System.Int32 cONTRAT_NUM, global::System.String cONTRAT_NOM)
        {
            CONTRAT cONTRAT = new CONTRAT();
            cONTRAT.CONTRAT_NUM = cONTRAT_NUM;
            cONTRAT.CONTRAT_NOM = cONTRAT_NOM;
            return cONTRAT;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CONTRAT_NUM
        {
            get
            {
                return _CONTRAT_NUM;
            }
            set
            {
                if (_CONTRAT_NUM != value)
                {
                    OnCONTRAT_NUMChanging(value);
                    ReportPropertyChanging("CONTRAT_NUM");
                    _CONTRAT_NUM = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CONTRAT_NUM");
                    OnCONTRAT_NUMChanged();
                }
            }
        }
        private global::System.Int32 _CONTRAT_NUM;
        partial void OnCONTRAT_NUMChanging(global::System.Int32 value);
        partial void OnCONTRAT_NUMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONTRAT_NOM
        {
            get
            {
                return _CONTRAT_NOM;
            }
            set
            {
                OnCONTRAT_NOMChanging(value);
                ReportPropertyChanging("CONTRAT_NOM");
                _CONTRAT_NOM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CONTRAT_NOM");
                OnCONTRAT_NOMChanged();
            }
        }
        private global::System.String _CONTRAT_NOM;
        partial void OnCONTRAT_NOMChanging(global::System.String value);
        partial void OnCONTRAT_NOMChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_SIGNE_CONTRAT", "SIGNE")]
        public EntityCollection<SIGNE> SIGNE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SIGNE>("GRHProjectModel.FK_SIGNE_CONTRAT", "SIGNE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SIGNE>("GRHProjectModel.FK_SIGNE_CONTRAT", "SIGNE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="DIPLOME")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DIPLOME : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet DIPLOME.
        /// </summary>
        /// <param name="dIPLOME_ID">Valeur initiale de la propriété DIPLOME_ID.</param>
        public static DIPLOME CreateDIPLOME(global::System.Int32 dIPLOME_ID)
        {
            DIPLOME dIPLOME = new DIPLOME();
            dIPLOME.DIPLOME_ID = dIPLOME_ID;
            return dIPLOME;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DIPLOME_ID
        {
            get
            {
                return _DIPLOME_ID;
            }
            set
            {
                if (_DIPLOME_ID != value)
                {
                    OnDIPLOME_IDChanging(value);
                    ReportPropertyChanging("DIPLOME_ID");
                    _DIPLOME_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DIPLOME_ID");
                    OnDIPLOME_IDChanged();
                }
            }
        }
        private global::System.Int32 _DIPLOME_ID;
        partial void OnDIPLOME_IDChanging(global::System.Int32 value);
        partial void OnDIPLOME_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIPLOME_NOM
        {
            get
            {
                return _DIPLOME_NOM;
            }
            set
            {
                OnDIPLOME_NOMChanging(value);
                ReportPropertyChanging("DIPLOME_NOM");
                _DIPLOME_NOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIPLOME_NOM");
                OnDIPLOME_NOMChanged();
            }
        }
        private global::System.String _DIPLOME_NOM;
        partial void OnDIPLOME_NOMChanging(global::System.String value);
        partial void OnDIPLOME_NOMChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "POSSEDE", "EMPLOYE")]
        public EntityCollection<EMPLOYE> LesEmployes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EMPLOYE>("GRHProjectModel.POSSEDE", "EMPLOYE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EMPLOYE>("GRHProjectModel.POSSEDE", "EMPLOYE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="EMPLOYE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EMPLOYE : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet EMPLOYE.
        /// </summary>
        /// <param name="eMP_ID">Valeur initiale de la propriété EMP_ID.</param>
        /// <param name="eMP_NOM">Valeur initiale de la propriété EMP_NOM.</param>
        /// <param name="eMP_PRENOM">Valeur initiale de la propriété EMP_PRENOM.</param>
        /// <param name="eMP_ADRESSE">Valeur initiale de la propriété EMP_ADRESSE.</param>
        /// <param name="eMP_CP">Valeur initiale de la propriété EMP_CP.</param>
        /// <param name="eMP_VILLE">Valeur initiale de la propriété EMP_VILLE.</param>
        /// <param name="sERV_ID">Valeur initiale de la propriété SERV_ID.</param>
        /// <param name="mET_ID">Valeur initiale de la propriété MET_ID.</param>
        public static EMPLOYE CreateEMPLOYE(global::System.Int32 eMP_ID, global::System.String eMP_NOM, global::System.String eMP_PRENOM, global::System.String eMP_ADRESSE, global::System.String eMP_CP, global::System.String eMP_VILLE, global::System.Int32 sERV_ID, global::System.Int32 mET_ID)
        {
            EMPLOYE eMPLOYE = new EMPLOYE();
            eMPLOYE.EMP_ID = eMP_ID;
            eMPLOYE.EMP_NOM = eMP_NOM;
            eMPLOYE.EMP_PRENOM = eMP_PRENOM;
            eMPLOYE.EMP_ADRESSE = eMP_ADRESSE;
            eMPLOYE.EMP_CP = eMP_CP;
            eMPLOYE.EMP_VILLE = eMP_VILLE;
            eMPLOYE.SERV_ID = sERV_ID;
            eMPLOYE.MET_ID = mET_ID;
            return eMPLOYE;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EMP_ID
        {
            get
            {
                return _EMP_ID;
            }
            set
            {
                if (_EMP_ID != value)
                {
                    OnEMP_IDChanging(value);
                    ReportPropertyChanging("EMP_ID");
                    _EMP_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EMP_ID");
                    OnEMP_IDChanged();
                }
            }
        }
        private global::System.Int32 _EMP_ID;
        partial void OnEMP_IDChanging(global::System.Int32 value);
        partial void OnEMP_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMP_NOM
        {
            get
            {
                return _EMP_NOM;
            }
            set
            {
                OnEMP_NOMChanging(value);
                ReportPropertyChanging("EMP_NOM");
                _EMP_NOM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMP_NOM");
                OnEMP_NOMChanged();
            }
        }
        private global::System.String _EMP_NOM;
        partial void OnEMP_NOMChanging(global::System.String value);
        partial void OnEMP_NOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMP_PRENOM
        {
            get
            {
                return _EMP_PRENOM;
            }
            set
            {
                OnEMP_PRENOMChanging(value);
                ReportPropertyChanging("EMP_PRENOM");
                _EMP_PRENOM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMP_PRENOM");
                OnEMP_PRENOMChanged();
            }
        }
        private global::System.String _EMP_PRENOM;
        partial void OnEMP_PRENOMChanging(global::System.String value);
        partial void OnEMP_PRENOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMP_ADRESSE
        {
            get
            {
                return _EMP_ADRESSE;
            }
            set
            {
                OnEMP_ADRESSEChanging(value);
                ReportPropertyChanging("EMP_ADRESSE");
                _EMP_ADRESSE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMP_ADRESSE");
                OnEMP_ADRESSEChanged();
            }
        }
        private global::System.String _EMP_ADRESSE;
        partial void OnEMP_ADRESSEChanging(global::System.String value);
        partial void OnEMP_ADRESSEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMP_CP
        {
            get
            {
                return _EMP_CP;
            }
            set
            {
                OnEMP_CPChanging(value);
                ReportPropertyChanging("EMP_CP");
                _EMP_CP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMP_CP");
                OnEMP_CPChanged();
            }
        }
        private global::System.String _EMP_CP;
        partial void OnEMP_CPChanging(global::System.String value);
        partial void OnEMP_CPChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMP_VILLE
        {
            get
            {
                return _EMP_VILLE;
            }
            set
            {
                OnEMP_VILLEChanging(value);
                ReportPropertyChanging("EMP_VILLE");
                _EMP_VILLE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMP_VILLE");
                OnEMP_VILLEChanged();
            }
        }
        private global::System.String _EMP_VILLE;
        partial void OnEMP_VILLEChanging(global::System.String value);
        partial void OnEMP_VILLEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMP_TEL
        {
            get
            {
                return _EMP_TEL;
            }
            set
            {
                OnEMP_TELChanging(value);
                ReportPropertyChanging("EMP_TEL");
                _EMP_TEL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMP_TEL");
                OnEMP_TELChanged();
            }
        }
        private global::System.String _EMP_TEL;
        partial void OnEMP_TELChanging(global::System.String value);
        partial void OnEMP_TELChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMP_MAIL
        {
            get
            {
                return _EMP_MAIL;
            }
            set
            {
                OnEMP_MAILChanging(value);
                ReportPropertyChanging("EMP_MAIL");
                _EMP_MAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMP_MAIL");
                OnEMP_MAILChanged();
            }
        }
        private global::System.String _EMP_MAIL;
        partial void OnEMP_MAILChanging(global::System.String value);
        partial void OnEMP_MAILChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMP_SEXE
        {
            get
            {
                return _EMP_SEXE;
            }
            set
            {
                OnEMP_SEXEChanging(value);
                ReportPropertyChanging("EMP_SEXE");
                _EMP_SEXE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMP_SEXE");
                OnEMP_SEXEChanged();
            }
        }
        private global::System.String _EMP_SEXE;
        partial void OnEMP_SEXEChanging(global::System.String value);
        partial void OnEMP_SEXEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SERV_ID
        {
            get
            {
                return _SERV_ID;
            }
            set
            {
                OnSERV_IDChanging(value);
                ReportPropertyChanging("SERV_ID");
                _SERV_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SERV_ID");
                OnSERV_IDChanged();
            }
        }
        private global::System.Int32 _SERV_ID;
        partial void OnSERV_IDChanging(global::System.Int32 value);
        partial void OnSERV_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MET_ID
        {
            get
            {
                return _MET_ID;
            }
            set
            {
                OnMET_IDChanging(value);
                ReportPropertyChanging("MET_ID");
                _MET_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MET_ID");
                OnMET_IDChanged();
            }
        }
        private global::System.Int32 _MET_ID;
        partial void OnMET_IDChanging(global::System.Int32 value);
        partial void OnMET_IDChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_EST_GERE_PAR_EMPLOYE", "EST_GERE_PAR")]
        public EntityCollection<EST_GERE_PAR> EST_GERE_PAR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EST_GERE_PAR>("GRHProjectModel.FK_EST_GERE_PAR_EMPLOYE", "EST_GERE_PAR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EST_GERE_PAR>("GRHProjectModel.FK_EST_GERE_PAR_EMPLOYE", "EST_GERE_PAR", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_SIGNE_EMPLOYE", "SIGNE")]
        public EntityCollection<SIGNE> SIGNE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SIGNE>("GRHProjectModel.FK_SIGNE_EMPLOYE", "SIGNE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SIGNE>("GRHProjectModel.FK_SIGNE_EMPLOYE", "SIGNE", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "AVOIR", "ABSENCE")]
        public EntityCollection<ABSENCE> LesAbsences
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ABSENCE>("GRHProjectModel.AVOIR", "ABSENCE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ABSENCE>("GRHProjectModel.AVOIR", "ABSENCE", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "DISPOSE", "COMPETENCE")]
        public EntityCollection<COMPETENCE> LesCompetences
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COMPETENCE>("GRHProjectModel.DISPOSE", "COMPETENCE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COMPETENCE>("GRHProjectModel.DISPOSE", "COMPETENCE", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "POSSEDE", "DIPLOME")]
        public EntityCollection<DIPLOME> LesDiplomes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DIPLOME>("GRHProjectModel.POSSEDE", "DIPLOME");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DIPLOME>("GRHProjectModel.POSSEDE", "DIPLOME", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_EMPLOYE_METIER", "METIER")]
        public METIER LesMetiers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<METIER>("GRHProjectModel.FK_EMPLOYE_METIER", "METIER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<METIER>("GRHProjectModel.FK_EMPLOYE_METIER", "METIER").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<METIER> LesMetiersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<METIER>("GRHProjectModel.FK_EMPLOYE_METIER", "METIER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<METIER>("GRHProjectModel.FK_EMPLOYE_METIER", "METIER", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_EMPLOYE_SERVICE", "SERVICE")]
        public SERVICE LesServices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SERVICE>("GRHProjectModel.FK_EMPLOYE_SERVICE", "SERVICE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SERVICE>("GRHProjectModel.FK_EMPLOYE_SERVICE", "SERVICE").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SERVICE> LesServicesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SERVICE>("GRHProjectModel.FK_EMPLOYE_SERVICE", "SERVICE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SERVICE>("GRHProjectModel.FK_EMPLOYE_SERVICE", "SERVICE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="EST_GERE_PAR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EST_GERE_PAR : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet EST_GERE_PAR.
        /// </summary>
        /// <param name="eMP_ID">Valeur initiale de la propriété EMP_ID.</param>
        /// <param name="sERVICE_ID">Valeur initiale de la propriété SERVICE_ID.</param>
        public static EST_GERE_PAR CreateEST_GERE_PAR(global::System.Int32 eMP_ID, global::System.Int32 sERVICE_ID)
        {
            EST_GERE_PAR eST_GERE_PAR = new EST_GERE_PAR();
            eST_GERE_PAR.EMP_ID = eMP_ID;
            eST_GERE_PAR.SERVICE_ID = sERVICE_ID;
            return eST_GERE_PAR;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EMP_ID
        {
            get
            {
                return _EMP_ID;
            }
            set
            {
                if (_EMP_ID != value)
                {
                    OnEMP_IDChanging(value);
                    ReportPropertyChanging("EMP_ID");
                    _EMP_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EMP_ID");
                    OnEMP_IDChanged();
                }
            }
        }
        private global::System.Int32 _EMP_ID;
        partial void OnEMP_IDChanging(global::System.Int32 value);
        partial void OnEMP_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SERVICE_ID
        {
            get
            {
                return _SERVICE_ID;
            }
            set
            {
                if (_SERVICE_ID != value)
                {
                    OnSERVICE_IDChanging(value);
                    ReportPropertyChanging("SERVICE_ID");
                    _SERVICE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SERVICE_ID");
                    OnSERVICE_IDChanged();
                }
            }
        }
        private global::System.Int32 _SERVICE_ID;
        partial void OnSERVICE_IDChanging(global::System.Int32 value);
        partial void OnSERVICE_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE_DEBUTG
        {
            get
            {
                return _DATE_DEBUTG;
            }
            set
            {
                OnDATE_DEBUTGChanging(value);
                ReportPropertyChanging("DATE_DEBUTG");
                _DATE_DEBUTG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_DEBUTG");
                OnDATE_DEBUTGChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE_DEBUTG;
        partial void OnDATE_DEBUTGChanging(Nullable<global::System.DateTime> value);
        partial void OnDATE_DEBUTGChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE_FING
        {
            get
            {
                return _DATE_FING;
            }
            set
            {
                OnDATE_FINGChanging(value);
                ReportPropertyChanging("DATE_FING");
                _DATE_FING = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_FING");
                OnDATE_FINGChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE_FING;
        partial void OnDATE_FINGChanging(Nullable<global::System.DateTime> value);
        partial void OnDATE_FINGChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_EST_GERE_PAR_EMPLOYE", "EMPLOYE")]
        public EMPLOYE LesEmployes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPLOYE>("GRHProjectModel.FK_EST_GERE_PAR_EMPLOYE", "EMPLOYE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPLOYE>("GRHProjectModel.FK_EST_GERE_PAR_EMPLOYE", "EMPLOYE").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EMPLOYE> LesEmployesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPLOYE>("GRHProjectModel.FK_EST_GERE_PAR_EMPLOYE", "EMPLOYE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EMPLOYE>("GRHProjectModel.FK_EST_GERE_PAR_EMPLOYE", "EMPLOYE", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_EST_GERE_PAR_SERVICE", "SERVICE")]
        public SERVICE LeService
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SERVICE>("GRHProjectModel.FK_EST_GERE_PAR_SERVICE", "SERVICE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SERVICE>("GRHProjectModel.FK_EST_GERE_PAR_SERVICE", "SERVICE").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SERVICE> LeServiceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SERVICE>("GRHProjectModel.FK_EST_GERE_PAR_SERVICE", "SERVICE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SERVICE>("GRHProjectModel.FK_EST_GERE_PAR_SERVICE", "SERVICE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="HISTORIQUE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HISTORIQUE : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet HISTORIQUE.
        /// </summary>
        /// <param name="hISTORIQUE_ID">Valeur initiale de la propriété HISTORIQUE_ID.</param>
        /// <param name="hISTORIQUE_LIBELLE">Valeur initiale de la propriété HISTORIQUE_LIBELLE.</param>
        /// <param name="hISTORIQUE_DATE">Valeur initiale de la propriété HISTORIQUE_DATE.</param>
        public static HISTORIQUE CreateHISTORIQUE(global::System.Int32 hISTORIQUE_ID, global::System.String hISTORIQUE_LIBELLE, global::System.DateTime hISTORIQUE_DATE)
        {
            HISTORIQUE hISTORIQUE = new HISTORIQUE();
            hISTORIQUE.HISTORIQUE_ID = hISTORIQUE_ID;
            hISTORIQUE.HISTORIQUE_LIBELLE = hISTORIQUE_LIBELLE;
            hISTORIQUE.HISTORIQUE_DATE = hISTORIQUE_DATE;
            return hISTORIQUE;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HISTORIQUE_ID
        {
            get
            {
                return _HISTORIQUE_ID;
            }
            set
            {
                if (_HISTORIQUE_ID != value)
                {
                    OnHISTORIQUE_IDChanging(value);
                    ReportPropertyChanging("HISTORIQUE_ID");
                    _HISTORIQUE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HISTORIQUE_ID");
                    OnHISTORIQUE_IDChanged();
                }
            }
        }
        private global::System.Int32 _HISTORIQUE_ID;
        partial void OnHISTORIQUE_IDChanging(global::System.Int32 value);
        partial void OnHISTORIQUE_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HISTORIQUE_LIBELLE
        {
            get
            {
                return _HISTORIQUE_LIBELLE;
            }
            set
            {
                OnHISTORIQUE_LIBELLEChanging(value);
                ReportPropertyChanging("HISTORIQUE_LIBELLE");
                _HISTORIQUE_LIBELLE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HISTORIQUE_LIBELLE");
                OnHISTORIQUE_LIBELLEChanged();
            }
        }
        private global::System.String _HISTORIQUE_LIBELLE;
        partial void OnHISTORIQUE_LIBELLEChanging(global::System.String value);
        partial void OnHISTORIQUE_LIBELLEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HISTORIQUE_DATE
        {
            get
            {
                return _HISTORIQUE_DATE;
            }
            set
            {
                OnHISTORIQUE_DATEChanging(value);
                ReportPropertyChanging("HISTORIQUE_DATE");
                _HISTORIQUE_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HISTORIQUE_DATE");
                OnHISTORIQUE_DATEChanged();
            }
        }
        private global::System.DateTime _HISTORIQUE_DATE;
        partial void OnHISTORIQUE_DATEChanging(global::System.DateTime value);
        partial void OnHISTORIQUE_DATEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="METIER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class METIER : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet METIER.
        /// </summary>
        /// <param name="mETIER_ID">Valeur initiale de la propriété METIER_ID.</param>
        public static METIER CreateMETIER(global::System.Int32 mETIER_ID)
        {
            METIER mETIER = new METIER();
            mETIER.METIER_ID = mETIER_ID;
            return mETIER;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 METIER_ID
        {
            get
            {
                return _METIER_ID;
            }
            set
            {
                if (_METIER_ID != value)
                {
                    OnMETIER_IDChanging(value);
                    ReportPropertyChanging("METIER_ID");
                    _METIER_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("METIER_ID");
                    OnMETIER_IDChanged();
                }
            }
        }
        private global::System.Int32 _METIER_ID;
        partial void OnMETIER_IDChanging(global::System.Int32 value);
        partial void OnMETIER_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String METIER_NOM
        {
            get
            {
                return _METIER_NOM;
            }
            set
            {
                OnMETIER_NOMChanging(value);
                ReportPropertyChanging("METIER_NOM");
                _METIER_NOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("METIER_NOM");
                OnMETIER_NOMChanged();
            }
        }
        private global::System.String _METIER_NOM;
        partial void OnMETIER_NOMChanging(global::System.String value);
        partial void OnMETIER_NOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String METIER_DETAILS
        {
            get
            {
                return _METIER_DETAILS;
            }
            set
            {
                OnMETIER_DETAILSChanging(value);
                ReportPropertyChanging("METIER_DETAILS");
                _METIER_DETAILS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("METIER_DETAILS");
                OnMETIER_DETAILSChanged();
            }
        }
        private global::System.String _METIER_DETAILS;
        partial void OnMETIER_DETAILSChanging(global::System.String value);
        partial void OnMETIER_DETAILSChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_EMPLOYE_METIER", "EMPLOYE")]
        public EntityCollection<EMPLOYE> LesEmployes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EMPLOYE>("GRHProjectModel.FK_EMPLOYE_METIER", "EMPLOYE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EMPLOYE>("GRHProjectModel.FK_EMPLOYE_METIER", "EMPLOYE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="SERVICE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SERVICE : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet SERVICE.
        /// </summary>
        /// <param name="sERVICE_ID">Valeur initiale de la propriété SERVICE_ID.</param>
        /// <param name="sERVICE_DESIGNATION">Valeur initiale de la propriété SERVICE_DESIGNATION.</param>
        /// <param name="sERVICE_TYPE">Valeur initiale de la propriété SERVICE_TYPE.</param>
        /// <param name="sERVICE_CAPACITE">Valeur initiale de la propriété SERVICE_CAPACITE.</param>
        public static SERVICE CreateSERVICE(global::System.Int32 sERVICE_ID, global::System.String sERVICE_DESIGNATION, global::System.String sERVICE_TYPE, global::System.Int32 sERVICE_CAPACITE)
        {
            SERVICE sERVICE = new SERVICE();
            sERVICE.SERVICE_ID = sERVICE_ID;
            sERVICE.SERVICE_DESIGNATION = sERVICE_DESIGNATION;
            sERVICE.SERVICE_TYPE = sERVICE_TYPE;
            sERVICE.SERVICE_CAPACITE = sERVICE_CAPACITE;
            return sERVICE;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SERVICE_ID
        {
            get
            {
                return _SERVICE_ID;
            }
            set
            {
                if (_SERVICE_ID != value)
                {
                    OnSERVICE_IDChanging(value);
                    ReportPropertyChanging("SERVICE_ID");
                    _SERVICE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SERVICE_ID");
                    OnSERVICE_IDChanged();
                }
            }
        }
        private global::System.Int32 _SERVICE_ID;
        partial void OnSERVICE_IDChanging(global::System.Int32 value);
        partial void OnSERVICE_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SERVICE_DESIGNATION
        {
            get
            {
                return _SERVICE_DESIGNATION;
            }
            set
            {
                OnSERVICE_DESIGNATIONChanging(value);
                ReportPropertyChanging("SERVICE_DESIGNATION");
                _SERVICE_DESIGNATION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SERVICE_DESIGNATION");
                OnSERVICE_DESIGNATIONChanged();
            }
        }
        private global::System.String _SERVICE_DESIGNATION;
        partial void OnSERVICE_DESIGNATIONChanging(global::System.String value);
        partial void OnSERVICE_DESIGNATIONChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SERVICE_TYPE
        {
            get
            {
                return _SERVICE_TYPE;
            }
            set
            {
                OnSERVICE_TYPEChanging(value);
                ReportPropertyChanging("SERVICE_TYPE");
                _SERVICE_TYPE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SERVICE_TYPE");
                OnSERVICE_TYPEChanged();
            }
        }
        private global::System.String _SERVICE_TYPE;
        partial void OnSERVICE_TYPEChanging(global::System.String value);
        partial void OnSERVICE_TYPEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SERVICE_CAPACITE
        {
            get
            {
                return _SERVICE_CAPACITE;
            }
            set
            {
                OnSERVICE_CAPACITEChanging(value);
                ReportPropertyChanging("SERVICE_CAPACITE");
                _SERVICE_CAPACITE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SERVICE_CAPACITE");
                OnSERVICE_CAPACITEChanged();
            }
        }
        private global::System.Int32 _SERVICE_CAPACITE;
        partial void OnSERVICE_CAPACITEChanging(global::System.Int32 value);
        partial void OnSERVICE_CAPACITEChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_EST_GERE_PAR_SERVICE", "EST_GERE_PAR")]
        public EntityCollection<EST_GERE_PAR> EST_GERE_PAR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EST_GERE_PAR>("GRHProjectModel.FK_EST_GERE_PAR_SERVICE", "EST_GERE_PAR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EST_GERE_PAR>("GRHProjectModel.FK_EST_GERE_PAR_SERVICE", "EST_GERE_PAR", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_EMPLOYE_SERVICE", "EMPLOYE")]
        public EntityCollection<EMPLOYE> LesEmployes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EMPLOYE>("GRHProjectModel.FK_EMPLOYE_SERVICE", "EMPLOYE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EMPLOYE>("GRHProjectModel.FK_EMPLOYE_SERVICE", "EMPLOYE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="SIGNE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SIGNE : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet SIGNE.
        /// </summary>
        /// <param name="cONTRAT_NUM">Valeur initiale de la propriété CONTRAT_NUM.</param>
        /// <param name="eMP_ID">Valeur initiale de la propriété EMP_ID.</param>
        /// <param name="sALAIRE">Valeur initiale de la propriété SALAIRE.</param>
        /// <param name="dATE_DEBUTS">Valeur initiale de la propriété DATE_DEBUTS.</param>
        public static SIGNE CreateSIGNE(global::System.Int32 cONTRAT_NUM, global::System.Int32 eMP_ID, global::System.Int32 sALAIRE, global::System.DateTime dATE_DEBUTS)
        {
            SIGNE sIGNE = new SIGNE();
            sIGNE.CONTRAT_NUM = cONTRAT_NUM;
            sIGNE.EMP_ID = eMP_ID;
            sIGNE.SALAIRE = sALAIRE;
            sIGNE.DATE_DEBUTS = dATE_DEBUTS;
            return sIGNE;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CONTRAT_NUM
        {
            get
            {
                return _CONTRAT_NUM;
            }
            set
            {
                if (_CONTRAT_NUM != value)
                {
                    OnCONTRAT_NUMChanging(value);
                    ReportPropertyChanging("CONTRAT_NUM");
                    _CONTRAT_NUM = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CONTRAT_NUM");
                    OnCONTRAT_NUMChanged();
                }
            }
        }
        private global::System.Int32 _CONTRAT_NUM;
        partial void OnCONTRAT_NUMChanging(global::System.Int32 value);
        partial void OnCONTRAT_NUMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EMP_ID
        {
            get
            {
                return _EMP_ID;
            }
            set
            {
                if (_EMP_ID != value)
                {
                    OnEMP_IDChanging(value);
                    ReportPropertyChanging("EMP_ID");
                    _EMP_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EMP_ID");
                    OnEMP_IDChanged();
                }
            }
        }
        private global::System.Int32 _EMP_ID;
        partial void OnEMP_IDChanging(global::System.Int32 value);
        partial void OnEMP_IDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SALAIRE
        {
            get
            {
                return _SALAIRE;
            }
            set
            {
                OnSALAIREChanging(value);
                ReportPropertyChanging("SALAIRE");
                _SALAIRE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SALAIRE");
                OnSALAIREChanged();
            }
        }
        private global::System.Int32 _SALAIRE;
        partial void OnSALAIREChanging(global::System.Int32 value);
        partial void OnSALAIREChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATE_DEBUTS
        {
            get
            {
                return _DATE_DEBUTS;
            }
            set
            {
                OnDATE_DEBUTSChanging(value);
                ReportPropertyChanging("DATE_DEBUTS");
                _DATE_DEBUTS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_DEBUTS");
                OnDATE_DEBUTSChanged();
            }
        }
        private global::System.DateTime _DATE_DEBUTS;
        partial void OnDATE_DEBUTSChanging(global::System.DateTime value);
        partial void OnDATE_DEBUTSChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_SIGNE_CONTRAT", "CONTRAT")]
        public CONTRAT LesContrats
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRAT>("GRHProjectModel.FK_SIGNE_CONTRAT", "CONTRAT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRAT>("GRHProjectModel.FK_SIGNE_CONTRAT", "CONTRAT").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CONTRAT> LesContratsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRAT>("GRHProjectModel.FK_SIGNE_CONTRAT", "CONTRAT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CONTRAT>("GRHProjectModel.FK_SIGNE_CONTRAT", "CONTRAT", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GRHProjectModel", "FK_SIGNE_EMPLOYE", "EMPLOYE")]
        public EMPLOYE LesEmployes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPLOYE>("GRHProjectModel.FK_SIGNE_EMPLOYE", "EMPLOYE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPLOYE>("GRHProjectModel.FK_SIGNE_EMPLOYE", "EMPLOYE").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EMPLOYE> LesEmployesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPLOYE>("GRHProjectModel.FK_SIGNE_EMPLOYE", "EMPLOYE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EMPLOYE>("GRHProjectModel.FK_SIGNE_EMPLOYE", "EMPLOYE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GRHProjectModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet sysdiagrams.
        /// </summary>
        /// <param name="name">Valeur initiale de la propriété name.</param>
        /// <param name="principal_id">Valeur initiale de la propriété principal_id.</param>
        /// <param name="diagram_id">Valeur initiale de la propriété diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
